apiVersion: v1
kind: Service
metadata:
  name: safedeploy-ci-cd-service
  namespace: default
spec:
  selector:
    app: devops
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP 